name: KapipDayZ
version: 1.5.3
description: Kapip created DAYZ plugin!
author: Mr_Burkes
website: http://kapip.com

main: org.kapip.dayz.Main
database: false

commands:
    dump:
        Permission: kapipdayz.dump
        Usage: /dump
        Description: Dump the item in your hand.
        Default: true
        aliases: [d]
        
    stopforce:
        Permission: kapipdayz.stop
        Usage: /stopforce
        Description: RAHH.
        Default: true
    unstopforce:
        Permission: kapipdayz.stop
        Usage: /unstopforce
        Description: UNRAHH.
        Default: true
